#!/usr/local/php/bin/php
<?php
	require('godinit.php');

	$result = '';
	if ($argc >= 2) {
		/*if ($argv[1] == '-v') {
			$result = godinit::$VERSION;
		} else if ($argv[1] == 'init') {
			$result = godinit::init();
		} else if ($argv[1] == 'make') {
			$result = godinit::make();
		}*/

		// 方法名变量
		$p = $argv[1];
		if (substr($p, 0, 1) == '-') {
			godinit::$p;
		}
		godinit::$p();
		exit();

        /*'-v' == $argv[1] && $result = godinit::$VERSION;
        'init' == $argv[1] && $result = godinit::init();
        'make' == $argv[1] && $result = godinit::make();*/
	}

	echo $result;
	echo PHP_EOL;
